### PR TITLE
Deploy GitHub Actions artifacts to Pages

### PR DESCRIPTION
**Pull request by keta1**
image
需将 [page 来源](https://github.com/mincong-h/mincong-h.github.io/settings/pages) 设置为 GitHub Action

### CODE REVIEW

**Review by mincong-h — APPROVED** [review]
Let's try this, thanks 😁 谢谢

**Comment by mincong-h** [comment]
Does it mean that we don't need to use the `gh-pages` branch anymore?

**Comment by mincong-h** [comment]
It looks pretty cool! https://github.com/mincong-h/mincong-h.github.io/actions/runs/4095592589

**Comment by keta1** [comment]
> Does it mean that we don't need to use the `gh-pages` branch anymore?

yes

**Comment by mincong-h** [comment]
Thanks a lot for the PR and the explanation. In the future, I will let you know whenever I update anything related to Jekyll TeXt Theme so you could consider changing yours as well.

**Comment by keta1** [comment]
> Thanks a lot for the PR and the explanation. In the future, I will let you know whenever I update things related to Jekyll TeXt Theme so you could consider changing yours as well.

I have watched this repo, the changes are visibled.
Recently, I've been working on the button to switch between English and Chinese sites via the flag button. If an article has a corresponding page in another language, I want to be able to switch to that corresponding page via this page.
But I haven't found a suitable solution for implementation.

**Comment by keta1** [comment]
the style of the flag button is also different from the style of the search button near to it, which looks a bit abrupt

**Comment by mincong-h** [comment]
You can see this article as an example https://mincong.io/en/elasticsearch-settings/, by clicking the "CN" icon, you can switch to https://mincong.io/cn/elasticsearch-settings/ It's done around the lines below in the "article-info.html", where we iterate through two collections of the website: "posts" `site.posts` (English) and "cn" `site.cn` (Chinese) by using the same article short id (without the collection prefix)

https://github.com/mincong-h/mincong-h.github.io/blob/c10fe558bbecb2fda67a273bf1155c9513b8ff4f/_includes/article-info.html#L62-L98

That button won't show if you don't have the "show_lang" settings enabled, or don't have the corresponding Chines article. I documented some of those changes in my previous article https://mincong.io/cn/jekyll-i18n/#任务六语言切换按钮 but it's mainly a self-talk post.

**Comment by mincong-h** [comment]
> the style of the flag button is also different from the style of the search button near to it, which looks a bit abrupt

We need a UI designer, I am pretty bad on that 😅 but I am happy to hear your suggestion

**Comment by keta1** [comment]
> You can see this article as an example https://mincong.io/en/elasticsearch-settings/, by clicking the "CN" icon, you can switch to https://mincong.io/cn/elasticsearch-settings/ It's done around the lines below in the "article-info.html", where we iterate through two collections of the website: "posts" `site.posts` (English) and "cn" `site.cn` (Chinese) by using the same article short id (without the collection prefix)
> 
> https://github.com/mincong-h/mincong-h.github.io/blob/c10fe558bbecb2fda67a273bf1155c9513b8ff4f/_includes/article-info.html#L62-L98
> 
> That button won't show if you don't have the "show_lang" settings enabled, or don't have the corresponding Chines article. I documented some of those changes in my previous article [https://mincong.io/cn/jekyll-i18n/#任务六语言切换按钮](https://mincong.io/cn/jekyll-i18n/#%E4%BB%BB%E5%8A%A1%E5%85%AD%E8%AF%AD%E8%A8%80%E5%88%87%E6%8D%A2%E6%8C%89%E9%92%AE) but it's mainly a self-talk post.

I have tried to implement it myself before, but it feels clumsy to do so.
I did overlook the "show_lang" settings
> https://github.com/keta1/keta1.github.io/commit/406ede

**Pull request merged**
